#!/bin/bash

# Author: Hlomane
# Created: 23 October 2023 - 2:56 PM
# Last Modified: 23 October 2023 - 2:56 PM

# Description: 
# Generates bash script template file with with user executable permissions 

# Usage:
# script-gen filename

# Create the file with user execute permissions
script_name=$1
touch $script_name
chmod u+x $script_name

cat << EOF > $script_name
#!/bin/bash

# Author: $USER
# Created: $( date "+%d %B %Y - %H:%M:%S" )
# Last Modified: $( date "+%d %B %Y - %H:%M:%S" )

# Description: 
# [Add short description about the script]

# Usage:
# $script_name [param]

main()
{
    echo "Hello, World!"
    exit
}

main
EOF